name: Download CS Game Files (Force)

on:
    workflow_dispatch:

jobs:
    download:
        runs-on: ubuntu-latest

        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
            contents: write

        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v3
            - name: Download new game files
              run: npm install && node index.js '${{ secrets.USERNAME }}' '${{ secrets.PASSWORD }}' --force
            - name: Run Decompiler for pak01_dir.vpk with ValveResourceFormat 11.1
              run: |
                  if [ -f "./temp/pak01_dir.vpk" ]; then
                    rm -fr ./exceptions.txt
                    chmod +x ./Source2Viewer-CLI
                    ./Source2Viewer-CLI -i "./temp/pak01_dir.vpk" -o "./static" -e "vtex_c" -d -f "panorama/images/econ"
                  else
                    echo "pak01_dir.vpk not found, skipping decompilation"
                  fi
            - name: Generate default_generated.json
              run: node list.js
            - name: Read manifestId.txt
              id: manifestId
              uses: juliangruber/read-file-action@v1
              with:
                  path: ./static/manifestId.txt
            - name: Commit & push changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "manifest ${{ steps.manifestId.outputs.content }}"
